config/routes.rb
Helper40App::Application.routes.draw do
  resources :orders

end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Helper4.0App</title>

        <script src = "libs/json2.js"></script>
        <script src = "libs/jquery.js"></script>
        <script src = "libs/underscore.js"></script>
        <script src = "libs/backbone.js"></script>
        <script src = "libs/backbone-localstorage.js"></script>
        <script src = "libs/backbone-mediator.js"></script>
        <script src = "libs/Backbone.ModelBinder.min.js"></script>
        
        <script src = "Order/TestModuleView.js"></script>
        <script src = "Order/OrderModel.js"></script>
        <script src = "Order/OrderView.js"></script>

        <script src = "Order/Run.js"></script>

        <link rel = "stylesheet" href = "Order css/Order.css">

        <script type = "text/template" id = "order_tpl" >

        <div class = "order_box">

            <p id="order_head"> Order</p>
            <div id="order_items" class="order_items">
                 <span id="sum"></span>
            </div>
                <input type = "button" id = "order_close" value = "Close order">  </input>
        </div>

        </script>
        
         <script>        
            $(function() {   
            
                $.ajaxSetup({                 
                    headers:{
                        'X-CSRF-Token':$('meta[name="csrf-token"]').attr('content')
                    }                      
                }); 
                
            });
        </script>   

        
        
        
        <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<div id = "container">

        <div id = "order_container" >

        </div>
            <div id = "testmodule">
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
            </br>
            <input type = "button" id = "table_order_new" value = "new">  </input>
            <input type = "button" id = "table_order_show" value = "show">  </input>
            <input type = "button" id = "menu_order_new" value = "menu_item to order_items">  </input>

            </div>
</div>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>